### ISSUE TITLE
当有遮罩层的时候我觉得首页是不可以滑动的

### ISSUE THREAD

**Issue by wangdabaoqq** [cccyb/vue-zhihu-daily#3]

**Comment by cccyb** [comment]
是的，这个暂时是个bug，我知道的，但是我还没解决，下次会抽空去修复的。。。

**Comment by wangdabaoqq** [comment]
好的 持续关注中

**Comment by cccyb** [comment]
滑动穿透bug已接近，解决方法可以参考[移动端滚动穿透问题完美解决方案](https://uedsky.com/2016-06/mobile-modal-scroll/) ，但在线预览部署项目还未修改，可以下载代码至本地跑看效果@wangdabaoqq
