### ISSUE TITLE
轮播图的图片链接为什么要处理一下？

### ISSUE THREAD

**Issue by wyxt81** [cccyb/vue-zhihu-daily#4]
轮播图的图片链接为什么要处理过后，才能获取到？而直接写上不处理的链接就只能获取到一张？

**Comment by cccyb** [comment]
处理轮播图的图片链接是因为知乎对图片做了防盗链处理。
知乎API返回的数据中的图片都是存储在知乎服务器上的url地址，直接请求会返回403，所以需要进行一些处理，使用Images.weserv.nl进行缓存图片，并在需要使用图片url的地方进行相应的替换。
具体可以参考我的博客[http://chenyubo.me/2017/03/30/vue-zhihu-daily/#3-图片防盗链问题](http://chenyubo.me/2017/03/30/vue-zhihu-daily/#3-图片防盗链问题)
